/*
 * Automatically generated C config: don't edit
 * Linux kernel version: 2.6.11
 * Fri Dec  8 11:27:41 2017
 */
#define AUTOCONF_INCLUDED
#define CONFIG_X86_64 1
#define CONFIG_64BIT 1
#define CONFIG_X86 1
#define CONFIG_MMU 1
#define CONFIG_RWSEM_GENERIC_SPINLOCK 1
#define CONFIG_GENERIC_CALIBRATE_DELAY 1
#define CONFIG_X86_CMPXCHG 1
#define CONFIG_EARLY_PRINTK 1
#define CONFIG_HPET_TIMER 1
#define CONFIG_GENERIC_ISA_DMA 1
#define CONFIG_GENERIC_IOMAP 1

/*
 * Code maturity level options
 */
#define CONFIG_EXPERIMENTAL 1
#define CONFIG_CLEAN_COMPILE 1
#define CONFIG_LOCK_KERNEL 1

/*
 * General setup
 */
#define CONFIG_LOCALVERSION ""
#define CONFIG_SWAP 1
#define CONFIG_SYSVIPC 1
#define CONFIG_POSIX_MQUEUE 1
#define CONFIG_BSD_PROCESS_ACCT 1
#define CONFIG_BSD_PROCESS_ACCT_V3 1
#define CONFIG_SYSCTL 1
#define CONFIG_AUDIT 1
#define CONFIG_AUDITSYSCALL 1
#define CONFIG_LOG_BUF_SHIFT 18
#define CONFIG_HOTPLUG 1
#define CONFIG_KOBJECT_UEVENT 1
#define CONFIG_IKCONFIG 1
#define CONFIG_IKCONFIG_PROC 1
#define CONFIG_EMBEDDED 1
#define CONFIG_KALLSYMS 1
#define CONFIG_KALLSYMS_ALL 1
#undef CONFIG_KALLSYMS_EXTRA_PASS
#define CONFIG_FUTEX 1
#define CONFIG_EPOLL 1
#undef CONFIG_CC_OPTIMIZE_FOR_SIZE
#define CONFIG_SHMEM 1
#define CONFIG_CC_ALIGN_FUNCTIONS 0
#define CONFIG_CC_ALIGN_LABELS 0
#define CONFIG_CC_ALIGN_LOOPS 0
#define CONFIG_CC_ALIGN_JUMPS 0
#undef CONFIG_TINY_SHMEM

/*
 * Loadable module support
 */
#define CONFIG_MODULES 1
#define CONFIG_MODULE_UNLOAD 1
#define CONFIG_MODULE_FORCE_UNLOAD 1
#define CONFIG_OBSOLETE_MODPARM 1
#define CONFIG_MODVERSIONS 1
#define CONFIG_MODULE_SRCVERSION_ALL 1
#define CONFIG_KMOD 1
#define CONFIG_STOP_MACHINE 1

/*
 * Processor type and features
 */
#undef CONFIG_MK8
#undef CONFIG_MPSC
#define CONFIG_GENERIC_CPU 1
#define CONFIG_X86_L1_CACHE_BYTES 128
#define CONFIG_X86_L1_CACHE_SHIFT 7
#define CONFIG_X86_TSC 1
#define CONFIG_X86_GOOD_APIC 1
#define CONFIG_MICROCODE 1
#define CONFIG_X86_MSR 1
#define CONFIG_X86_CPUID 1
#define CONFIG_X86_HT 1
#define CONFIG_X86_IO_APIC 1
#define CONFIG_X86_LOCAL_APIC 1
#define CONFIG_MTRR 1
#define CONFIG_SMP 1
#define CONFIG_PREEMPT 1
#define CONFIG_PREEMPT_BKL 1
#define CONFIG_SCHED_SMT 1
#define CONFIG_K8_NUMA 1
#define CONFIG_NUMA_EMU 1
#define CONFIG_DISCONTIGMEM 1
#define CONFIG_NUMA 1
#define CONFIG_HAVE_DEC_LOCK 1
#define CONFIG_NR_CPUS 8
#define CONFIG_GART_IOMMU 1
#define CONFIG_SWIOTLB 1
#define CONFIG_X86_MCE 1
#define CONFIG_X86_MCE_INTEL 1
#define CONFIG_GENERIC_HARDIRQS 1
#define CONFIG_GENERIC_IRQ_PROBE 1

/*
 * Power management options
 */
#define CONFIG_PM 1
#define CONFIG_PM_DEBUG 1
#define CONFIG_SOFTWARE_SUSPEND 1
#define CONFIG_PM_STD_PARTITION ""

/*
 * ACPI (Advanced Configuration and Power Interface) Support
 */
#define CONFIG_ACPI 1
#define CONFIG_ACPI_BOOT 1
#define CONFIG_ACPI_INTERPRETER 1
#define CONFIG_ACPI_SLEEP 1
#define CONFIG_ACPI_SLEEP_PROC_FS 1
#define CONFIG_ACPI_AC 1
#define CONFIG_ACPI_BATTERY 1
#define CONFIG_ACPI_BUTTON 1
#define CONFIG_ACPI_VIDEO_MODULE 1
#define CONFIG_ACPI_FAN 1
#define CONFIG_ACPI_PROCESSOR 1
#define CONFIG_ACPI_THERMAL 1
#undef CONFIG_ACPI_NUMA
#define CONFIG_ACPI_ASUS_MODULE 1
#define CONFIG_ACPI_IBM_MODULE 1
#define CONFIG_ACPI_TOSHIBA_MODULE 1
#define CONFIG_ACPI_BLACKLIST_YEAR 0
#undef CONFIG_ACPI_DEBUG
#define CONFIG_ACPI_BUS 1
#define CONFIG_ACPI_EC 1
#define CONFIG_ACPI_POWER 1
#define CONFIG_ACPI_PCI 1
#define CONFIG_ACPI_SYSTEM 1
#undef CONFIG_ACPI_CONTAINER

/*
 * CPU Frequency scaling
 */
#define CONFIG_CPU_FREQ 1
#undef CONFIG_CPU_FREQ_DEBUG
#define CONFIG_CPU_FREQ_STAT 1
#undef CONFIG_CPU_FREQ_STAT_DETAILS
#define CONFIG_CPU_FREQ_DEFAULT_GOV_PERFORMANCE 1
#undef CONFIG_CPU_FREQ_DEFAULT_GOV_USERSPACE
#define CONFIG_CPU_FREQ_GOV_PERFORMANCE 1
#define CONFIG_CPU_FREQ_GOV_POWERSAVE 1
#define CONFIG_CPU_FREQ_GOV_USERSPACE 1
#define CONFIG_CPU_FREQ_GOV_ONDEMAND 1
#define CONFIG_CPU_FREQ_TABLE 1

/*
 * CPUFreq processor drivers
 */
#define CONFIG_X86_POWERNOW_K8_MODULE 1
#define CONFIG_X86_POWERNOW_K8_ACPI 1
#undef CONFIG_X86_SPEEDSTEP_CENTRINO
#define CONFIG_X86_ACPI_CPUFREQ_MODULE 1

/*
 * shared options
 */
#undef CONFIG_X86_ACPI_CPUFREQ_PROC_INTF
#undef CONFIG_X86_P4_CLOCKMOD

/*
 * Bus options (PCI etc.)
 */
#define CONFIG_PCI 1
#define CONFIG_PCI_DIRECT 1
#define CONFIG_PCI_MMCONFIG 1
#undef CONFIG_UNORDERED_IO
#define CONFIG_PCI_MSI 1
#undef CONFIG_PCI_LEGACY_PROC
#undef CONFIG_PCI_NAMES

/*
 * PCCARD (PCMCIA/CardBus) support
 */
#define CONFIG_PCCARD 1
#undef CONFIG_PCMCIA_DEBUG
#define CONFIG_PCMCIA 1
#define CONFIG_CARDBUS 1

/*
 * PC-card bridges
 */
#define CONFIG_YENTA_MODULE 1
#define CONFIG_PD6729_MODULE 1
#define CONFIG_I82092_MODULE 1
#undef CONFIG_TCIC
#define CONFIG_PCCARD_NONSTATIC_MODULE 1

/*
 * PCI Hotplug Support
 */
#undef CONFIG_HOTPLUG_PCI

/*
 * Executable file formats / Emulations
 */
#define CONFIG_BINFMT_ELF 1
#define CONFIG_BINFMT_MISC_MODULE 1
#define CONFIG_IA32_EMULATION 1
#undef CONFIG_IA32_AOUT
#define CONFIG_COMPAT 1
#define CONFIG_SYSVIPC_COMPAT 1
#define CONFIG_UID16 1

/*
 * Device Drivers
 */

/*
 * Generic Driver Options
 */
#define CONFIG_STANDALONE 1
#define CONFIG_PREVENT_FIRMWARE_BUILD 1
#define CONFIG_FW_LOADER 1
#undef CONFIG_DEBUG_DRIVER

/*
 * Memory Technology Devices (MTD)
 */
#define CONFIG_MTD_MODULE 1
#undef CONFIG_MTD_DEBUG
#undef CONFIG_MTD_PARTITIONS
#undef CONFIG_MTD_CONCAT

/*
 * User Modules And Translation Layers
 */
#undef CONFIG_MTD_CHAR
#define CONFIG_MTD_BLOCK_MODULE 1
#undef CONFIG_MTD_BLOCK_RO
#undef CONFIG_FTL
#undef CONFIG_NFTL
#undef CONFIG_INFTL

/*
 * RAM/ROM/Flash chip drivers
 */
#undef CONFIG_MTD_CFI
#undef CONFIG_MTD_JEDECPROBE
#define CONFIG_MTD_MAP_BANK_WIDTH_1 1
#define CONFIG_MTD_MAP_BANK_WIDTH_2 1
#define CONFIG_MTD_MAP_BANK_WIDTH_4 1
#undef CONFIG_MTD_MAP_BANK_WIDTH_8
#undef CONFIG_MTD_MAP_BANK_WIDTH_16
#undef CONFIG_MTD_MAP_BANK_WIDTH_32
#define CONFIG_MTD_CFI_I1 1
#define CONFIG_MTD_CFI_I2 1
#undef CONFIG_MTD_CFI_I4
#undef CONFIG_MTD_CFI_I8
#undef CONFIG_MTD_RAM
#undef CONFIG_MTD_ROM
#undef CONFIG_MTD_ABSENT

/*
 * Mapping drivers for chip access
 */
#undef CONFIG_MTD_COMPLEX_MAPPINGS

/*
 * Self-contained MTD device drivers
 */
#undef CONFIG_MTD_PMC551
#undef CONFIG_MTD_SLRAM
#undef CONFIG_MTD_PHRAM
#undef CONFIG_MTD_MTDRAM
#undef CONFIG_MTD_BLKMTD
#undef CONFIG_MTD_BLOCK2MTD

/*
 * Disk-On-Chip Device Drivers
 */
#undef CONFIG_MTD_DOC2000
#undef CONFIG_MTD_DOC2001
#undef CONFIG_MTD_DOC2001PLUS

/*
 * NAND Flash Device Drivers
 */
#undef CONFIG_MTD_NAND

/*
 * Parallel port support
 */
#define CONFIG_PARPORT_MODULE 1
#define CONFIG_PARPORT_PC_MODULE 1
#define CONFIG_PARPORT_PC_CML1_MODULE 1
#define CONFIG_PARPORT_SERIAL_MODULE 1
#undef CONFIG_PARPORT_PC_FIFO
#undef CONFIG_PARPORT_PC_SUPERIO
#define CONFIG_PARPORT_PC_PCMCIA_MODULE 1
#undef CONFIG_PARPORT_OTHER
#define CONFIG_PARPORT_1284 1

/*
 * Plug and Play support
 */
#define CONFIG_PNP 1
#undef CONFIG_PNP_DEBUG

/*
 * Protocols
 */
#define CONFIG_PNPACPI 1

/*
 * Block devices
 */
#define CONFIG_BLK_DEV_FD_MODULE 1
#undef CONFIG_PARIDE
#undef CONFIG_BLK_CPQ_DA
#define CONFIG_BLK_CPQ_CISS_DA_MODULE 1
#define CONFIG_CISS_SCSI_TAPE 1
#define CONFIG_BLK_DEV_DAC960_MODULE 1
#undef CONFIG_BLK_DEV_UMEM
#undef CONFIG_BLK_DEV_COW_COMMON
#define CONFIG_BLK_DEV_LOOP_MODULE 1
#undef CONFIG_BLK_DEV_CRYPTOLOOP
#define CONFIG_BLK_DEV_NBD_MODULE 1
#define CONFIG_BLK_DEV_SX8_MODULE 1
#undef CONFIG_BLK_DEV_UB
#define CONFIG_BLK_DEV_RAM_MODULE 1
#define CONFIG_BLK_DEV_RAM_COUNT 16
#define CONFIG_BLK_DEV_RAM_SIZE 16384
#define CONFIG_INITRAMFS_SOURCE ""
#undef CONFIG_LBD
#define CONFIG_CDROM_PKTCDVD_MODULE 1
#define CONFIG_CDROM_PKTCDVD_BUFFERS 8
#undef CONFIG_CDROM_PKTCDVD_WCACHE

/*
 * IO Schedulers
 */
#define CONFIG_IOSCHED_NOOP 1
#define CONFIG_IOSCHED_AS 1
#define CONFIG_IOSCHED_DEADLINE 1
#define CONFIG_IOSCHED_CFQ 1
#define CONFIG_ATA_OVER_ETH_MODULE 1

/*
 * ATA/ATAPI/MFM/RLL support
 */
#undef CONFIG_IDE

/*
 * SCSI device support
 */
#define CONFIG_SCSI 1
#define CONFIG_SCSI_PROC_FS 1

/*
 * SCSI support type (disk, tape, CD-ROM)
 */
#define CONFIG_BLK_DEV_SD 1
#define CONFIG_CHR_DEV_ST_MODULE 1
#define CONFIG_CHR_DEV_OSST_MODULE 1
#define CONFIG_BLK_DEV_SR 1
#define CONFIG_BLK_DEV_SR_VENDOR 1
#define CONFIG_CHR_DEV_SG 1

/*
 * Some SCSI devices (e.g. CD jukebox) support multiple LUNs
 */
#undef CONFIG_SCSI_MULTI_LUN
#define CONFIG_SCSI_CONSTANTS 1
#define CONFIG_SCSI_LOGGING 1

/*
 * SCSI Transport Attributes
 */
#define CONFIG_SCSI_SPI_ATTRS_MODULE 1
#define CONFIG_SCSI_FC_ATTRS_MODULE 1
#define CONFIG_SCSI_ISCSI_ATTRS_MODULE 1

/*
 * SCSI low-level drivers
 */
#define CONFIG_BLK_DEV_3W_XXXX_RAID_MODULE 1
#define CONFIG_SCSI_3W_9XXX_MODULE 1
#define CONFIG_SCSI_ACARD_MODULE 1
#define CONFIG_SCSI_AACRAID_MODULE 1
#define CONFIG_SCSI_AIC7XXX_MODULE 1
#define CONFIG_AIC7XXX_CMDS_PER_DEVICE 4
#define CONFIG_AIC7XXX_RESET_DELAY_MS 15000
#undef CONFIG_AIC7XXX_DEBUG_ENABLE
#define CONFIG_AIC7XXX_DEBUG_MASK 0
#undef CONFIG_AIC7XXX_REG_PRETTY_PRINT
#undef CONFIG_SCSI_AIC7XXX_OLD
#define CONFIG_SCSI_AIC79XX_MODULE 1
#define CONFIG_AIC79XX_CMDS_PER_DEVICE 4
#define CONFIG_AIC79XX_RESET_DELAY_MS 15000
#undef CONFIG_AIC79XX_ENABLE_RD_STRM
#undef CONFIG_AIC79XX_DEBUG_ENABLE
#define CONFIG_AIC79XX_DEBUG_MASK 0
#undef CONFIG_AIC79XX_REG_PRETTY_PRINT
#define CONFIG_MEGARAID_NEWGEN 1
#define CONFIG_MEGARAID_MM_MODULE 1
#define CONFIG_MEGARAID_MAILBOX_MODULE 1
#undef CONFIG_SCSI_SATA
#define CONFIG_SCSI_BUSLOGIC_MODULE 1
#undef CONFIG_SCSI_OMIT_FLASHPOINT
#define CONFIG_SCSI_DMX3191D_MODULE 1
#undef CONFIG_SCSI_EATA
#undef CONFIG_SCSI_EATA_PIO
#undef CONFIG_SCSI_FUTURE_DOMAIN
#define CONFIG_SCSI_GDTH_MODULE 1
#define CONFIG_SCSI_IPS_MODULE 1
#define CONFIG_SCSI_INITIO_MODULE 1
#define CONFIG_SCSI_INIA100_MODULE 1
#undef CONFIG_SCSI_PPA
#undef CONFIG_SCSI_IMM
#define CONFIG_SCSI_SYM53C8XX_2_MODULE 1
#define CONFIG_SCSI_SYM53C8XX_DMA_ADDRESSING_MODE 1
#define CONFIG_SCSI_SYM53C8XX_DEFAULT_TAGS 16
#define CONFIG_SCSI_SYM53C8XX_MAX_TAGS 64
#undef CONFIG_SCSI_SYM53C8XX_IOMAPPED
#define CONFIG_SCSI_IPR_MODULE 1
#define CONFIG_SCSI_IPR_TRACE 1
#define CONFIG_SCSI_IPR_DUMP 1
#undef CONFIG_SCSI_QLOGIC_ISP
#undef CONFIG_SCSI_QLOGIC_FC
#define CONFIG_SCSI_QLOGIC_1280_MODULE 1
#undef CONFIG_SCSI_QLOGIC_1280_1040
#define CONFIG_SCSI_QLA2XXX 1
#undef CONFIG_SCSI_QLA21XX
#undef CONFIG_SCSI_QLA22XX
#undef CONFIG_SCSI_QLA2300
#undef CONFIG_SCSI_QLA2322
#undef CONFIG_SCSI_QLA6312
#undef CONFIG_SCSI_DC395x
#undef CONFIG_SCSI_DC390T
#define CONFIG_SCSI_DEBUG_MODULE 1

/*
 * PCMCIA SCSI adapter support
 */
#undef CONFIG_PCMCIA_FDOMAIN
#undef CONFIG_PCMCIA_QLOGIC
#undef CONFIG_PCMCIA_SYM53C500

/*
 * Multi-device support (RAID and LVM)
 */
#define CONFIG_MD 1
#define CONFIG_BLK_DEV_MD 1
#define CONFIG_MD_LINEAR_MODULE 1
#define CONFIG_MD_RAID0_MODULE 1
#define CONFIG_MD_RAID1_MODULE 1
#undef CONFIG_MD_RAID10
#undef CONFIG_MD_RAID5
#undef CONFIG_MD_RAID6
#define CONFIG_MD_MULTIPATH_MODULE 1
#define CONFIG_MD_FAULTY_MODULE 1
#define CONFIG_BLK_DEV_DM 1
#undef CONFIG_DM_CRYPT
#undef CONFIG_DM_SNAPSHOT
#undef CONFIG_DM_MIRROR
#undef CONFIG_DM_ZERO

/*
 * Fusion MPT device support
 */
#define CONFIG_FUSION 1
#define CONFIG_FUSION_MAX_SGE 40
#define CONFIG_FUSION_CTL_MODULE 1
#define CONFIG_FUSION_LAN_MODULE 1

/*
 * IEEE 1394 (FireWire) support
 */
#undef CONFIG_IEEE1394

/*
 * I2O device support
 */
#undef CONFIG_I2O

/*
 * Networking support
 */
#define CONFIG_NET 1

/*
 * Networking options
 */
#define CONFIG_PACKET 1
#undef CONFIG_PACKET_MMAP
#undef CONFIG_NETLINK_DEV
#define CONFIG_UNIX 1
#define CONFIG_NET_KEY_MODULE 1
#define CONFIG_INET 1
#define CONFIG_IP_MULTICAST 1
#define CONFIG_IP_ADVANCED_ROUTER 1
#define CONFIG_IP_MULTIPLE_TABLES 1
#undef CONFIG_IP_ROUTE_FWMARK
#define CONFIG_IP_ROUTE_MULTIPATH 1
#define CONFIG_IP_ROUTE_VERBOSE 1
#undef CONFIG_IP_PNP
#define CONFIG_NET_IPIP_MODULE 1
#define CONFIG_NET_IPGRE_MODULE 1
#define CONFIG_NET_IPGRE_BROADCAST 1
#define CONFIG_IP_MROUTE 1
#define CONFIG_IP_PIMSM_V1 1
#define CONFIG_IP_PIMSM_V2 1
#undef CONFIG_ARPD
#define CONFIG_SYN_COOKIES 1
#define CONFIG_INET_AH_MODULE 1
#define CONFIG_INET_ESP_MODULE 1
#define CONFIG_INET_IPCOMP_MODULE 1
#define CONFIG_INET_TUNNEL_MODULE 1
#define CONFIG_IP_TCPDIAG 1
#undef CONFIG_IP_TCPDIAG_IPV6

/*
 * IP: Virtual Server Configuration
 */
#define CONFIG_IP_VS_MODULE 1
#undef CONFIG_IP_VS_DEBUG
#define CONFIG_IP_VS_TAB_BITS 12

/*
 * IPVS transport protocol load balancing support
 */
#define CONFIG_IP_VS_PROTO_TCP 1
#define CONFIG_IP_VS_PROTO_UDP 1
#define CONFIG_IP_VS_PROTO_ESP 1
#define CONFIG_IP_VS_PROTO_AH 1

/*
 * IPVS scheduler
 */
#define CONFIG_IP_VS_RR_MODULE 1
#define CONFIG_IP_VS_WRR_MODULE 1
#define CONFIG_IP_VS_LC_MODULE 1
#define CONFIG_IP_VS_WLC_MODULE 1
#define CONFIG_IP_VS_LBLC_MODULE 1
#define CONFIG_IP_VS_LBLCR_MODULE 1
#define CONFIG_IP_VS_DH_MODULE 1
#define CONFIG_IP_VS_SH_MODULE 1
#define CONFIG_IP_VS_SED_MODULE 1
#define CONFIG_IP_VS_NQ_MODULE 1

/*
 * IPVS application helper
 */
#define CONFIG_IP_VS_FTP_MODULE 1
#undef CONFIG_IPV6
#define CONFIG_NETFILTER 1
#undef CONFIG_NETFILTER_DEBUG
#define CONFIG_BRIDGE_NETFILTER 1

/*
 * IP: Netfilter Configuration
 */
#undef CONFIG_IP_NF_CONNTRACK
#undef CONFIG_IP_NF_CONNTRACK_MARK
#undef CONFIG_IP_NF_QUEUE
#define CONFIG_IP_NF_IPTABLES 1
#undef CONFIG_IP_NF_MATCH_LIMIT
#undef CONFIG_IP_NF_MATCH_IPRANGE
#undef CONFIG_IP_NF_MATCH_MAC
#undef CONFIG_IP_NF_MATCH_PKTTYPE
#undef CONFIG_IP_NF_MATCH_MARK
#undef CONFIG_IP_NF_MATCH_MULTIPORT
#undef CONFIG_IP_NF_MATCH_TOS
#undef CONFIG_IP_NF_MATCH_RECENT
#define CONFIG_IP_NF_MATCH_ECN_MODULE 1
#undef CONFIG_IP_NF_MATCH_DSCP
#undef CONFIG_IP_NF_MATCH_AH_ESP
#undef CONFIG_IP_NF_MATCH_LENGTH
#define CONFIG_IP_NF_MATCH_TTL_MODULE 1
#undef CONFIG_IP_NF_MATCH_TCPMSS
#undef CONFIG_IP_NF_MATCH_OWNER
#undef CONFIG_IP_NF_MATCH_PHYSDEV
#undef CONFIG_IP_NF_MATCH_ADDRTYPE
#undef CONFIG_IP_NF_MATCH_REALM
#undef CONFIG_IP_NF_MATCH_SCTP
#undef CONFIG_IP_NF_MATCH_COMMENT
#undef CONFIG_IP_NF_MATCH_HASHLIMIT
#define CONFIG_IP_NF_FILTER 1
#define CONFIG_IP_NF_TARGET_REJECT 1
#undef CONFIG_IP_NF_TARGET_LOG
#undef CONFIG_IP_NF_TARGET_ULOG
#undef CONFIG_IP_NF_TARGET_TCPMSS
#define CONFIG_IP_NF_MANGLE_MODULE 1
#undef CONFIG_IP_NF_TARGET_TOS
#define CONFIG_IP_NF_TARGET_ECN_MODULE 1
#undef CONFIG_IP_NF_TARGET_DSCP
#undef CONFIG_IP_NF_TARGET_MARK
#undef CONFIG_IP_NF_TARGET_CLASSIFY
#define CONFIG_IP_NF_RAW_MODULE 1
#define CONFIG_IP_NF_ARPTABLES_MODULE 1
#define CONFIG_IP_NF_ARPFILTER_MODULE 1
#define CONFIG_IP_NF_ARP_MANGLE_MODULE 1

/*
 * Bridge: Netfilter Configuration
 */
#define CONFIG_BRIDGE_NF_EBTABLES_MODULE 1
#define CONFIG_BRIDGE_EBT_BROUTE_MODULE 1
#define CONFIG_BRIDGE_EBT_T_FILTER_MODULE 1
#define CONFIG_BRIDGE_EBT_T_NAT_MODULE 1
#define CONFIG_BRIDGE_EBT_802_3_MODULE 1
#define CONFIG_BRIDGE_EBT_AMONG_MODULE 1
#define CONFIG_BRIDGE_EBT_ARP_MODULE 1
#define CONFIG_BRIDGE_EBT_IP_MODULE 1
#define CONFIG_BRIDGE_EBT_LIMIT_MODULE 1
#define CONFIG_BRIDGE_EBT_MARK_MODULE 1
#define CONFIG_BRIDGE_EBT_PKTTYPE_MODULE 1
#define CONFIG_BRIDGE_EBT_STP_MODULE 1
#define CONFIG_BRIDGE_EBT_VLAN_MODULE 1
#define CONFIG_BRIDGE_EBT_ARPREPLY_MODULE 1
#define CONFIG_BRIDGE_EBT_DNAT_MODULE 1
#define CONFIG_BRIDGE_EBT_MARK_T_MODULE 1
#define CONFIG_BRIDGE_EBT_REDIRECT_MODULE 1
#define CONFIG_BRIDGE_EBT_SNAT_MODULE 1
#define CONFIG_BRIDGE_EBT_LOG_MODULE 1
#undef CONFIG_BRIDGE_EBT_ULOG
#define CONFIG_XFRM 1
#define CONFIG_XFRM_USER 1

/*
 * SCTP Configuration (EXPERIMENTAL)
 */
#undef CONFIG_IP_SCTP
#undef CONFIG_ATM
#define CONFIG_BRIDGE_MODULE 1
#define CONFIG_VLAN_8021Q_MODULE 1
#undef CONFIG_DECNET
#define CONFIG_LLC_MODULE 1
#undef CONFIG_LLC2
#define CONFIG_IPX_MODULE 1
#undef CONFIG_IPX_INTERN
#define CONFIG_ATALK_MODULE 1
#undef CONFIG_DEV_APPLETALK
#undef CONFIG_X25
#undef CONFIG_LAPB
#undef CONFIG_NET_DIVERT
#undef CONFIG_ECONET
#undef CONFIG_WAN_ROUTER

/*
 * QoS and/or fair queueing
 */
#define CONFIG_NET_SCHED 1
#define CONFIG_NET_SCH_CLK_JIFFIES 1
#undef CONFIG_NET_SCH_CLK_GETTIMEOFDAY
#undef CONFIG_NET_SCH_CLK_CPU
#define CONFIG_NET_SCH_CBQ_MODULE 1
#define CONFIG_NET_SCH_HTB_MODULE 1
#define CONFIG_NET_SCH_HFSC_MODULE 1
#define CONFIG_NET_SCH_PRIO_MODULE 1
#define CONFIG_NET_SCH_RED_MODULE 1
#define CONFIG_NET_SCH_SFQ_MODULE 1
#define CONFIG_NET_SCH_TEQL_MODULE 1
#define CONFIG_NET_SCH_TBF_MODULE 1
#define CONFIG_NET_SCH_GRED_MODULE 1
#define CONFIG_NET_SCH_DSMARK_MODULE 1
#define CONFIG_NET_SCH_NETEM_MODULE 1
#define CONFIG_NET_SCH_INGRESS_MODULE 1
#undef CONFIG_NET_QOS
#define CONFIG_NET_CLS 1
#define CONFIG_NET_CLS_TCINDEX_MODULE 1
#define CONFIG_NET_CLS_ROUTE4_MODULE 1
#define CONFIG_NET_CLS_ROUTE 1
#define CONFIG_NET_CLS_FW_MODULE 1
#define CONFIG_NET_CLS_U32_MODULE 1
#define CONFIG_CLS_U32_PERF 1
#define CONFIG_NET_CLS_IND 1
#define CONFIG_CLS_U32_MARK 1

/*
 * Network testing
 */
#define CONFIG_NET_PKTGEN_MODULE 1
#undef CONFIG_NETPOLL
#undef CONFIG_NET_POLL_CONTROLLER
#define CONFIG_HAMRADIO 1

/*
 * Packet Radio protocols
 */
#define CONFIG_AX25_MODULE 1
#define CONFIG_AX25_DAMA_SLAVE 1
#define CONFIG_NETROM_MODULE 1
#define CONFIG_ROSE_MODULE 1

/*
 * AX.25 network device drivers
 */
#define CONFIG_BPQETHER_MODULE 1
#define CONFIG_BAYCOM_SER_FDX_MODULE 1
#define CONFIG_BAYCOM_SER_HDX_MODULE 1
#define CONFIG_BAYCOM_PAR_MODULE 1
#define CONFIG_YAM_MODULE 1
#define CONFIG_IRDA_MODULE 1

/*
 * IrDA protocols
 */
#define CONFIG_IRLAN_MODULE 1
#define CONFIG_IRNET_MODULE 1
#define CONFIG_IRCOMM_MODULE 1
#undef CONFIG_IRDA_ULTRA

/*
 * IrDA options
 */
#define CONFIG_IRDA_CACHE_LAST_LSAP 1
#define CONFIG_IRDA_FAST_RR 1
#undef CONFIG_IRDA_DEBUG

/*
 * Infrared-port device drivers
 */

/*
 * SIR device drivers
 */
#define CONFIG_IRTTY_SIR_MODULE 1

/*
 * Dongle support
 */
#define CONFIG_DONGLE 1
#define CONFIG_ESI_DONGLE_MODULE 1
#define CONFIG_ACTISYS_DONGLE_MODULE 1
#define CONFIG_TEKRAM_DONGLE_MODULE 1
#define CONFIG_LITELINK_DONGLE_MODULE 1
#undef CONFIG_MA600_DONGLE
#undef CONFIG_GIRBIL_DONGLE
#undef CONFIG_MCP2120_DONGLE
#undef CONFIG_OLD_BELKIN_DONGLE
#undef CONFIG_ACT200L_DONGLE

/*
 * Old SIR device drivers
 */

/*
 * Old Serial dongle support
 */

/*
 * FIR device drivers
 */
#define CONFIG_USB_IRDA_MODULE 1
#undef CONFIG_SIGMATEL_FIR
#undef CONFIG_VLSI_FIR
#define CONFIG_BT_MODULE 1
#undef CONFIG_BT_L2CAP
#undef CONFIG_BT_SCO

/*
 * Bluetooth device drivers
 */
#undef CONFIG_BT_HCIUSB
#define CONFIG_BT_HCIUART_MODULE 1
#define CONFIG_BT_HCIUART_H4 1
#define CONFIG_BT_HCIUART_BCSP 1
#undef CONFIG_BT_HCIUART_BCSP_TXCRC
#define CONFIG_BT_HCIBCM203X_MODULE 1
#define CONFIG_BT_HCIBPA10X_MODULE 1
#define CONFIG_BT_HCIBFUSB_MODULE 1
#define CONFIG_BT_HCIDTL1_MODULE 1
#define CONFIG_BT_HCIBT3C_MODULE 1
#define CONFIG_BT_HCIBLUECARD_MODULE 1
#define CONFIG_BT_HCIBTUART_MODULE 1
#define CONFIG_BT_HCIVHCI_MODULE 1
#define CONFIG_NETDEVICES 1
#define CONFIG_DUMMY_MODULE 1
#define CONFIG_BONDING_MODULE 1
#define CONFIG_EQUALIZER_MODULE 1
#define CONFIG_TUN_MODULE 1
#undef CONFIG_NET_SB1000

/*
 * ARCnet devices
 */
#undef CONFIG_ARCNET

/*
 * Ethernet (10 or 100Mbit)
 */
#undef CONFIG_NET_ETHERNET
#define CONFIG_MII_MODULE 1

/*
 * Ethernet (1000 Mbit)
 */
#define CONFIG_ACENIC_MODULE 1
#undef CONFIG_ACENIC_OMIT_TIGON_I
#define CONFIG_DL2K_MODULE 1
#define CONFIG_E1000_MODULE 1
#undef CONFIG_E1000_NAPI
#define CONFIG_NS83820_MODULE 1
#define CONFIG_HAMACHI_MODULE 1
#undef CONFIG_YELLOWFIN
#define CONFIG_R8169_MODULE 1
#undef CONFIG_R8169_NAPI
#undef CONFIG_R8169_VLAN
#undef CONFIG_SK98LIN
#define CONFIG_TIGON3_MODULE 1

/*
 * Ethernet (10000 Mbit)
 */
#define CONFIG_IXGB_MODULE 1
#undef CONFIG_IXGB_NAPI
#define CONFIG_S2IO_MODULE 1
#undef CONFIG_S2IO_NAPI
#undef CONFIG_2BUFF_MODE

/*
 * Token Ring devices
 */
#undef CONFIG_TR

/*
 * Wireless LAN (non-hamradio)
 */
#undef CONFIG_NET_RADIO

/*
 * PCMCIA network device support
 */
#undef CONFIG_NET_PCMCIA

/*
 * Wan interfaces
 */
#undef CONFIG_WAN
#undef CONFIG_FDDI
#undef CONFIG_HIPPI
#undef CONFIG_PLIP
#define CONFIG_PPP_MODULE 1
#undef CONFIG_PPP_MULTILINK
#define CONFIG_PPP_FILTER 1
#define CONFIG_PPP_ASYNC_MODULE 1
#define CONFIG_PPP_SYNC_TTY_MODULE 1
#define CONFIG_PPP_DEFLATE_MODULE 1
#define CONFIG_PPP_BSDCOMP_MODULE 1
#undef CONFIG_PPPOE
#define CONFIG_SLIP_MODULE 1
#define CONFIG_SLIP_COMPRESSED 1
#define CONFIG_SLIP_SMART 1
#undef CONFIG_SLIP_MODE_SLIP6
#define CONFIG_NET_FC 1
#undef CONFIG_SHAPER
#undef CONFIG_NETCONSOLE

/*
 * ISDN subsystem
 */
#define CONFIG_ISDN 1

/*
 * Old ISDN4Linux
 */
#define CONFIG_ISDN_I4L_MODULE 1
#define CONFIG_ISDN_PPP 1
#define CONFIG_ISDN_PPP_VJ 1
#define CONFIG_ISDN_MPP 1
#define CONFIG_IPPP_FILTER 1
#undef CONFIG_ISDN_PPP_BSDCOMP
#define CONFIG_ISDN_AUDIO 1
#define CONFIG_ISDN_TTY_FAX 1

/*
 * ISDN feature submodules
 */
#define CONFIG_ISDN_DIVERSION_MODULE 1

/*
 * ISDN4Linux hardware drivers
 */

/*
 * Passive cards
 */
#define CONFIG_ISDN_DRV_HISAX_MODULE 1

/*
 * D-channel protocol features
 */
#define CONFIG_HISAX_EURO 1
#define CONFIG_DE_AOC 1
#define CONFIG_HISAX_NO_SENDCOMPLETE 1
#define CONFIG_HISAX_NO_LLC 1
#define CONFIG_HISAX_NO_KEYPAD 1
#define CONFIG_HISAX_1TR6 1
#define CONFIG_HISAX_NI1 1
#define CONFIG_HISAX_MAX_CARDS 8

/*
 * HiSax supported cards
 */
#define CONFIG_HISAX_16_3 1
#define CONFIG_HISAX_TELESPCI 1
#define CONFIG_HISAX_S0BOX 1
#define CONFIG_HISAX_FRITZPCI 1
#define CONFIG_HISAX_AVM_A1_PCMCIA 1
#define CONFIG_HISAX_ELSA 1
#define CONFIG_HISAX_DIEHLDIVA 1
#define CONFIG_HISAX_SEDLBAUER 1
#define CONFIG_HISAX_NETJET 1
#define CONFIG_HISAX_NETJET_U 1
#define CONFIG_HISAX_NICCY 1
#define CONFIG_HISAX_BKM_A4T 1
#define CONFIG_HISAX_SCT_QUADRO 1
#define CONFIG_HISAX_GAZEL 1
#define CONFIG_HISAX_HFC_PCI 1
#define CONFIG_HISAX_W6692 1
#define CONFIG_HISAX_HFC_SX 1
#define CONFIG_HISAX_ENTERNOW_PCI 1
#undef CONFIG_HISAX_DEBUG

/*
 * HiSax PCMCIA card service modules
 */
#define CONFIG_HISAX_SEDLBAUER_CS_MODULE 1
#define CONFIG_HISAX_ELSA_CS_MODULE 1
#define CONFIG_HISAX_AVM_A1_CS_MODULE 1
#define CONFIG_HISAX_TELES_CS_MODULE 1

/*
 * HiSax sub driver modules
 */
#undef CONFIG_HISAX_ST5481
#undef CONFIG_HISAX_HFCUSB
#undef CONFIG_HISAX_FRITZ_PCIPNP

/*
 * Active cards
 */
#undef CONFIG_ISDN_DRV_TPAM

/*
 * CAPI subsystem
 */
#define CONFIG_ISDN_CAPI_MODULE 1
#undef CONFIG_ISDN_DRV_AVMB1_VERBOSE_REASON
#undef CONFIG_ISDN_CAPI_MIDDLEWARE
#define CONFIG_ISDN_CAPI_CAPI20_MODULE 1
#define CONFIG_ISDN_CAPI_CAPIDRV_MODULE 1

/*
 * CAPI hardware drivers
 */

/*
 * Active AVM cards
 */
#define CONFIG_CAPI_AVM 1
#define CONFIG_ISDN_DRV_AVMB1_B1PCI_MODULE 1
#define CONFIG_ISDN_DRV_AVMB1_B1PCIV4 1
#define CONFIG_ISDN_DRV_AVMB1_B1PCMCIA_MODULE 1
#define CONFIG_ISDN_DRV_AVMB1_AVM_CS_MODULE 1
#define CONFIG_ISDN_DRV_AVMB1_T1PCI_MODULE 1
#define CONFIG_ISDN_DRV_AVMB1_C4_MODULE 1

/*
 * Active Eicon DIVA Server cards
 */
#define CONFIG_CAPI_EICON 1
#define CONFIG_ISDN_DIVAS_MODULE 1
#define CONFIG_ISDN_DIVAS_BRIPCI 1
#define CONFIG_ISDN_DIVAS_PRIPCI 1
#define CONFIG_ISDN_DIVAS_DIVACAPI_MODULE 1
#define CONFIG_ISDN_DIVAS_USERIDI_MODULE 1
#define CONFIG_ISDN_DIVAS_MAINT_MODULE 1

/*
 * Telephony Support
 */
#undef CONFIG_PHONE

/*
 * Input device support
 */
#define CONFIG_INPUT 1

/*
 * Userland interfaces
 */
#define CONFIG_INPUT_MOUSEDEV 1
#undef CONFIG_INPUT_MOUSEDEV_PSAUX
#define CONFIG_INPUT_MOUSEDEV_SCREEN_X 1024
#define CONFIG_INPUT_MOUSEDEV_SCREEN_Y 768
#define CONFIG_INPUT_JOYDEV_MODULE 1
#undef CONFIG_INPUT_TSDEV
#define CONFIG_INPUT_EVDEV 1
#undef CONFIG_INPUT_EVBUG

/*
 * Input I/O drivers
 */
#define CONFIG_GAMEPORT_MODULE 1
#define CONFIG_SOUND_GAMEPORT_MODULE 1
#define CONFIG_GAMEPORT_NS558_MODULE 1
#define CONFIG_GAMEPORT_L4_MODULE 1
#define CONFIG_GAMEPORT_EMU10K1_MODULE 1
#undef CONFIG_GAMEPORT_VORTEX
#define CONFIG_GAMEPORT_FM801_MODULE 1
#undef CONFIG_GAMEPORT_CS461X
#define CONFIG_SERIO 1
#define CONFIG_SERIO_I8042 1
#define CONFIG_SERIO_SERPORT 1
#undef CONFIG_SERIO_CT82C710
#undef CONFIG_SERIO_PARKBD
#undef CONFIG_SERIO_PCIPS2
#define CONFIG_SERIO_LIBPS2 1
#define CONFIG_SERIO_RAW_MODULE 1

/*
 * Input Device Drivers
 */
#define CONFIG_INPUT_KEYBOARD 1
#define CONFIG_KEYBOARD_ATKBD 1
#undef CONFIG_KEYBOARD_SUNKBD
#undef CONFIG_KEYBOARD_LKKBD
#undef CONFIG_KEYBOARD_XTKBD
#undef CONFIG_KEYBOARD_NEWTON
#define CONFIG_INPUT_MOUSE 1
#define CONFIG_MOUSE_PS2 1
#define CONFIG_MOUSE_SERIAL_MODULE 1
#define CONFIG_MOUSE_VSXXXAA_MODULE 1
#define CONFIG_INPUT_JOYSTICK 1
#define CONFIG_JOYSTICK_ANALOG_MODULE 1
#define CONFIG_JOYSTICK_A3D_MODULE 1
#define CONFIG_JOYSTICK_ADI_MODULE 1
#define CONFIG_JOYSTICK_COBRA_MODULE 1
#define CONFIG_JOYSTICK_GF2K_MODULE 1
#define CONFIG_JOYSTICK_GRIP_MODULE 1
#define CONFIG_JOYSTICK_GRIP_MP_MODULE 1
#define CONFIG_JOYSTICK_GUILLEMOT_MODULE 1
#define CONFIG_JOYSTICK_INTERACT_MODULE 1
#define CONFIG_JOYSTICK_SIDEWINDER_MODULE 1
#define CONFIG_JOYSTICK_TMDC_MODULE 1
#define CONFIG_JOYSTICK_IFORCE_MODULE 1
#define CONFIG_JOYSTICK_IFORCE_USB 1
#define CONFIG_JOYSTICK_IFORCE_232 1
#define CONFIG_JOYSTICK_WARRIOR_MODULE 1
#define CONFIG_JOYSTICK_MAGELLAN_MODULE 1
#define CONFIG_JOYSTICK_SPACEORB_MODULE 1
#define CONFIG_JOYSTICK_SPACEBALL_MODULE 1
#define CONFIG_JOYSTICK_STINGER_MODULE 1
#undef CONFIG_JOYSTICK_TWIDDLER
#define CONFIG_JOYSTICK_DB9_MODULE 1
#define CONFIG_JOYSTICK_GAMECON_MODULE 1
#define CONFIG_JOYSTICK_TURBOGRAFX_MODULE 1
#define CONFIG_JOYSTICK_JOYDUMP_MODULE 1
#define CONFIG_INPUT_TOUCHSCREEN 1
#define CONFIG_TOUCHSCREEN_GUNZE_MODULE 1
#define CONFIG_INPUT_MISC 1
#define CONFIG_INPUT_PCSPKR_MODULE 1
#define CONFIG_INPUT_UINPUT_MODULE 1

/*
 * Character devices
 */
#define CONFIG_VT 1
#define CONFIG_VT_CONSOLE 1
#define CONFIG_HW_CONSOLE 1
#define CONFIG_SERIAL_NONSTANDARD 1
#define CONFIG_ROCKETPORT_MODULE 1
#define CONFIG_CYCLADES_MODULE 1
#undef CONFIG_CYZ_INTR
#undef CONFIG_MOXA_SMARTIO
#undef CONFIG_ISI
#define CONFIG_SYNCLINK_MODULE 1
#define CONFIG_SYNCLINKMP_MODULE 1
#define CONFIG_N_HDLC_MODULE 1
#undef CONFIG_STALDRV

/*
 * Serial drivers
 */
#define CONFIG_SERIAL_8250 1
#define CONFIG_SERIAL_8250_CONSOLE 1
#define CONFIG_SERIAL_8250_CS_MODULE 1
#undef CONFIG_SERIAL_8250_ACPI
#define CONFIG_SERIAL_8250_NR_UARTS 32
#define CONFIG_SERIAL_8250_EXTENDED 1
#define CONFIG_SERIAL_8250_MANY_PORTS 1
#define CONFIG_SERIAL_8250_SHARE_IRQ 1
#undef CONFIG_SERIAL_8250_DETECT_IRQ
#undef CONFIG_SERIAL_8250_MULTIPORT
#define CONFIG_SERIAL_8250_RSA 1

/*
 * Non-8250 serial port support
 */
#define CONFIG_SERIAL_CORE 1
#define CONFIG_SERIAL_CORE_CONSOLE 1
#define CONFIG_UNIX98_PTYS 1
#undef CONFIG_LEGACY_PTYS
#define CONFIG_PRINTER_MODULE 1
#define CONFIG_LP_CONSOLE 1
#define CONFIG_PPDEV_MODULE 1
#undef CONFIG_TIPAR

/*
 * IPMI
 */
#define CONFIG_IPMI_HANDLER_MODULE 1
#undef CONFIG_IPMI_PANIC_EVENT
#define CONFIG_IPMI_DEVICE_INTERFACE_MODULE 1
#define CONFIG_IPMI_SI_MODULE 1
#define CONFIG_IPMI_WATCHDOG_MODULE 1
#define CONFIG_IPMI_POWEROFF_MODULE 1

/*
 * Watchdog Cards
 */
#define CONFIG_WATCHDOG 1
#undef CONFIG_WATCHDOG_NOWAYOUT

/*
 * Watchdog Device Drivers
 */
#define CONFIG_SOFT_WATCHDOG_MODULE 1
#undef CONFIG_ACQUIRE_WDT
#undef CONFIG_ADVANTECH_WDT
#define CONFIG_ALIM1535_WDT_MODULE 1
#define CONFIG_ALIM7101_WDT_MODULE 1
#undef CONFIG_SC520_WDT
#undef CONFIG_EUROTECH_WDT
#define CONFIG_IB700_WDT_MODULE 1
#undef CONFIG_WAFER_WDT
#undef CONFIG_I8XX_TCO
#undef CONFIG_SC1200_WDT
#undef CONFIG_SCx200_WDT
#undef CONFIG_60XX_WDT
#undef CONFIG_CPU5_WDT
#define CONFIG_W83627HF_WDT_MODULE 1
#define CONFIG_W83877F_WDT_MODULE 1
#define CONFIG_MACHZ_WDT_MODULE 1

/*
 * PCI-based Watchdog Cards
 */
#define CONFIG_PCIPCWATCHDOG_MODULE 1
#define CONFIG_WDTPCI_MODULE 1
#undef CONFIG_WDT_501_PCI

/*
 * USB-based Watchdog Cards
 */
#define CONFIG_USBPCWATCHDOG_MODULE 1
#define CONFIG_HW_RANDOM 1
#define CONFIG_NVRAM 1
#undef CONFIG_RTC
#undef CONFIG_GEN_RTC
#undef CONFIG_DTLK
#define CONFIG_R3964_MODULE 1
#undef CONFIG_APPLICOM

/*
 * Ftape, the floppy tape device driver
 */
#define CONFIG_AGP 1
#define CONFIG_AGP_AMD64 1
#undef CONFIG_AGP_INTEL_MCH
#define CONFIG_DRM_MODULE 1
#undef CONFIG_DRM_TDFX
#undef CONFIG_DRM_R128
#define CONFIG_DRM_RADEON_MODULE 1
#undef CONFIG_DRM_MGA
#undef CONFIG_DRM_SIS

/*
 * PCMCIA character devices
 */
#undef CONFIG_SYNCLINK_CS
#define CONFIG_MWAVE_MODULE 1
#define CONFIG_RAW_DRIVER 1
#define CONFIG_HPET 1
#undef CONFIG_HPET_RTC_IRQ
#undef CONFIG_HPET_MMAP
#define CONFIG_MAX_RAW_DEVS 8192
#define CONFIG_HANGCHECK_TIMER_MODULE 1

/*
 * I2C support
 */
#define CONFIG_I2C 1
#define CONFIG_I2C_CHARDEV_MODULE 1

/*
 * I2C Algorithms
 */
#define CONFIG_I2C_ALGOBIT_MODULE 1
#undef CONFIG_I2C_ALGOPCF
#define CONFIG_I2C_ALGOPCA_MODULE 1

/*
 * I2C Hardware Bus support
 */
#undef CONFIG_I2C_ALI1535
#undef CONFIG_I2C_ALI1563
#undef CONFIG_I2C_ALI15X3
#undef CONFIG_I2C_AMD756
#undef CONFIG_I2C_AMD8111
#undef CONFIG_I2C_I801
#undef CONFIG_I2C_I810
#undef CONFIG_I2C_ISA
#undef CONFIG_I2C_NFORCE2
#define CONFIG_I2C_PARPORT_MODULE 1
#define CONFIG_I2C_PARPORT_LIGHT_MODULE 1
#undef CONFIG_I2C_PROSAVAGE
#undef CONFIG_I2C_SAVAGE4
#undef CONFIG_SCx200_ACB
#undef CONFIG_I2C_SIS5595
#undef CONFIG_I2C_SIS630
#undef CONFIG_I2C_SIS96X
#undef CONFIG_I2C_STUB
#undef CONFIG_I2C_VIA
#undef CONFIG_I2C_VIAPRO
#undef CONFIG_I2C_VOODOO3
#undef CONFIG_I2C_PCA_ISA

/*
 * Hardware Sensors Chip support
 */
#define CONFIG_I2C_SENSOR_MODULE 1
#undef CONFIG_SENSORS_ADM1021
#undef CONFIG_SENSORS_ADM1025
#undef CONFIG_SENSORS_ADM1026
#undef CONFIG_SENSORS_ADM1031
#undef CONFIG_SENSORS_ASB100
#undef CONFIG_SENSORS_DS1621
#undef CONFIG_SENSORS_FSCHER
#undef CONFIG_SENSORS_GL518SM
#undef CONFIG_SENSORS_IT87
#undef CONFIG_SENSORS_LM63
#undef CONFIG_SENSORS_LM75
#undef CONFIG_SENSORS_LM77
#undef CONFIG_SENSORS_LM78
#undef CONFIG_SENSORS_LM80
#define CONFIG_SENSORS_LM83_MODULE 1
#undef CONFIG_SENSORS_LM85
#undef CONFIG_SENSORS_LM87
#define CONFIG_SENSORS_LM90_MODULE 1
#undef CONFIG_SENSORS_MAX1619
#undef CONFIG_SENSORS_PC87360
#undef CONFIG_SENSORS_SMSC47B397
#undef CONFIG_SENSORS_SMSC47M1
#undef CONFIG_SENSORS_VIA686A
#undef CONFIG_SENSORS_W83781D
#undef CONFIG_SENSORS_W83L785TS
#undef CONFIG_SENSORS_W83627HF

/*
 * Other I2C Chip support
 */
#undef CONFIG_SENSORS_EEPROM
#undef CONFIG_SENSORS_PCF8574
#undef CONFIG_SENSORS_PCF8591
#undef CONFIG_SENSORS_RTC8564
#undef CONFIG_I2C_DEBUG_CORE
#undef CONFIG_I2C_DEBUG_ALGO
#undef CONFIG_I2C_DEBUG_BUS
#undef CONFIG_I2C_DEBUG_CHIP

/*
 * Dallas's 1-wire bus
 */
#define CONFIG_W1_MODULE 1
#undef CONFIG_W1_MATROX
#undef CONFIG_W1_DS9490
#undef CONFIG_W1_THERM
#undef CONFIG_W1_SMEM

/*
 * Misc devices
 */
#undef CONFIG_IBM_ASM

/*
 * Multimedia devices
 */
#define CONFIG_VIDEO_DEV_MODULE 1

/*
 * Video For Linux
 */

/*
 * Video Adapters
 */
#define CONFIG_VIDEO_BT848_MODULE 1
#undef CONFIG_VIDEO_BWQCAM
#undef CONFIG_VIDEO_CQCAM
#undef CONFIG_VIDEO_W9966
#undef CONFIG_VIDEO_CPIA
#undef CONFIG_VIDEO_SAA5246A
#undef CONFIG_VIDEO_SAA5249
#undef CONFIG_TUNER_3036
#undef CONFIG_VIDEO_STRADIS
#define CONFIG_VIDEO_ZORAN_MODULE 1
#define CONFIG_VIDEO_ZORAN_BUZ_MODULE 1
#define CONFIG_VIDEO_ZORAN_DC10_MODULE 1
#define CONFIG_VIDEO_ZORAN_DC30_MODULE 1
#define CONFIG_VIDEO_ZORAN_LML33_MODULE 1
#define CONFIG_VIDEO_ZORAN_LML33R10_MODULE 1
#define CONFIG_VIDEO_SAA7134_MODULE 1
#define CONFIG_VIDEO_MXB_MODULE 1
#undef CONFIG_VIDEO_DPC
#define CONFIG_VIDEO_HEXIUM_ORION_MODULE 1
#define CONFIG_VIDEO_HEXIUM_GEMINI_MODULE 1
#undef CONFIG_VIDEO_CX88
#undef CONFIG_VIDEO_OVCAMCHIP

/*
 * Radio Adapters
 */
#undef CONFIG_RADIO_GEMTEK_PCI
#define CONFIG_RADIO_MAXIRADIO_MODULE 1
#undef CONFIG_RADIO_MAESTRO

/*
 * Digital Video Broadcasting Devices
 */
#undef CONFIG_DVB
#define CONFIG_VIDEO_SAA7146_MODULE 1
#define CONFIG_VIDEO_SAA7146_VV_MODULE 1
#define CONFIG_VIDEO_VIDEOBUF_MODULE 1
#define CONFIG_VIDEO_TUNER_MODULE 1
#define CONFIG_VIDEO_BUF_MODULE 1
#define CONFIG_VIDEO_BTCX_MODULE 1
#define CONFIG_VIDEO_IR_MODULE 1
#define CONFIG_VIDEO_TVEEPROM_MODULE 1

/*
 * Graphics support
 */
#define CONFIG_FB 1
#undef CONFIG_FB_MODE_HELPERS
#define CONFIG_FB_TILEBLITTING 1
#undef CONFIG_FB_CIRRUS
#undef CONFIG_FB_PM2
#undef CONFIG_FB_CYBER2000
#undef CONFIG_FB_ASILIANT
#undef CONFIG_FB_IMSTT
#define CONFIG_FB_VGA16_MODULE 1
#define CONFIG_FB_VESA 1
#define CONFIG_VIDEO_SELECT 1
#undef CONFIG_FB_HGA
#undef CONFIG_FB_RIVA
#undef CONFIG_FB_MATROX
#undef CONFIG_FB_RADEON_OLD
#undef CONFIG_FB_RADEON
#undef CONFIG_FB_ATY128
#undef CONFIG_FB_ATY
#undef CONFIG_FB_SAVAGE
#undef CONFIG_FB_SIS
#undef CONFIG_FB_NEOMAGIC
#undef CONFIG_FB_KYRO
#undef CONFIG_FB_3DFX
#undef CONFIG_FB_VOODOO1
#undef CONFIG_FB_TRIDENT
#define CONFIG_FB_VIRTUAL_MODULE 1

/*
 * Console display driver support
 */
#define CONFIG_VGA_CONSOLE 1
#define CONFIG_DUMMY_CONSOLE 1
#define CONFIG_FRAMEBUFFER_CONSOLE 1
#undef CONFIG_FONTS
#define CONFIG_FONT_8x8 1
#define CONFIG_FONT_8x16 1

/*
 * Logo configuration
 */
#define CONFIG_LOGO 1
#undef CONFIG_LOGO_LINUX_MONO
#undef CONFIG_LOGO_LINUX_VGA16
#define CONFIG_LOGO_LINUX_CLUT224 1
#define CONFIG_BACKLIGHT_LCD_SUPPORT 1
#define CONFIG_BACKLIGHT_CLASS_DEVICE 1
#define CONFIG_BACKLIGHT_DEVICE 1
#define CONFIG_LCD_CLASS_DEVICE_MODULE 1
#define CONFIG_LCD_DEVICE 1

/*
 * Sound
 */
#define CONFIG_SOUND_MODULE 1

/*
 * Advanced Linux Sound Architecture
 */
#define CONFIG_SND_MODULE 1
#define CONFIG_SND_TIMER_MODULE 1
#define CONFIG_SND_PCM_MODULE 1
#define CONFIG_SND_HWDEP_MODULE 1
#define CONFIG_SND_RAWMIDI_MODULE 1
#define CONFIG_SND_SEQUENCER_MODULE 1
#define CONFIG_SND_SEQ_DUMMY_MODULE 1
#define CONFIG_SND_OSSEMUL 1
#define CONFIG_SND_MIXER_OSS_MODULE 1
#define CONFIG_SND_PCM_OSS_MODULE 1
#undef CONFIG_SND_SEQUENCER_OSS
#undef CONFIG_SND_BIT32_EMUL
#undef CONFIG_SND_VERBOSE_PRINTK
#undef CONFIG_SND_DEBUG

/*
 * Generic devices
 */
#define CONFIG_SND_MPU401_UART_MODULE 1
#define CONFIG_SND_OPL3_LIB_MODULE 1
#define CONFIG_SND_VX_LIB_MODULE 1
#define CONFIG_SND_DUMMY_MODULE 1
#define CONFIG_SND_VIRMIDI_MODULE 1
#define CONFIG_SND_MTPAV_MODULE 1
#define CONFIG_SND_SERIAL_U16550_MODULE 1
#define CONFIG_SND_MPU401_MODULE 1

/*
 * PCI devices
 */
#define CONFIG_SND_AC97_CODEC_MODULE 1
#define CONFIG_SND_ALI5451_MODULE 1
#define CONFIG_SND_ATIIXP_MODULE 1
#define CONFIG_SND_ATIIXP_MODEM_MODULE 1
#define CONFIG_SND_AU8810_MODULE 1
#define CONFIG_SND_AU8820_MODULE 1
#define CONFIG_SND_AU8830_MODULE 1
#undef CONFIG_SND_AZT3328
#define CONFIG_SND_BT87X_MODULE 1
#undef CONFIG_SND_BT87X_OVERCLOCK
#define CONFIG_SND_CS46XX_MODULE 1
#undef CONFIG_SND_CS46XX_NEW_DSP
#define CONFIG_SND_CS4281_MODULE 1
#define CONFIG_SND_EMU10K1_MODULE 1
#define CONFIG_SND_EMU10K1X_MODULE 1
#define CONFIG_SND_CA0106_MODULE 1
#define CONFIG_SND_KORG1212_MODULE 1
#define CONFIG_SND_MIXART_MODULE 1
#define CONFIG_SND_NM256_MODULE 1
#define CONFIG_SND_RME32_MODULE 1
#define CONFIG_SND_RME96_MODULE 1
#define CONFIG_SND_RME9652_MODULE 1
#define CONFIG_SND_HDSP_MODULE 1
#define CONFIG_SND_TRIDENT_MODULE 1
#define CONFIG_SND_YMFPCI_MODULE 1
#define CONFIG_SND_ALS4000_MODULE 1
#define CONFIG_SND_CMIPCI_MODULE 1
#define CONFIG_SND_ENS1370_MODULE 1
#define CONFIG_SND_ENS1371_MODULE 1
#define CONFIG_SND_ES1938_MODULE 1
#define CONFIG_SND_ES1968_MODULE 1
#define CONFIG_SND_MAESTRO3_MODULE 1
#define CONFIG_SND_FM801_MODULE 1
#undef CONFIG_SND_FM801_TEA575X
#define CONFIG_SND_ICE1712_MODULE 1
#define CONFIG_SND_ICE1724_MODULE 1
#define CONFIG_SND_INTEL8X0_MODULE 1
#undef CONFIG_SND_INTEL8X0M
#define CONFIG_SND_SONICVIBES_MODULE 1
#define CONFIG_SND_VIA82XX_MODULE 1
#define CONFIG_SND_VIA82XX_MODEM_MODULE 1
#define CONFIG_SND_VX222_MODULE 1

/*
 * USB devices
 */
#define CONFIG_SND_USB_AUDIO_MODULE 1
#define CONFIG_SND_USB_USX2Y_MODULE 1

/*
 * PCMCIA devices
 */

/*
 * Open Sound System
 */
#undef CONFIG_SOUND_PRIME

/*
 * USB support
 */
#define CONFIG_USB 1
#undef CONFIG_USB_DEBUG

/*
 * Miscellaneous USB options
 */
#undef CONFIG_USB_DEVICEFS
#undef CONFIG_USB_BANDWIDTH
#undef CONFIG_USB_DYNAMIC_MINORS
#undef CONFIG_USB_SUSPEND
#undef CONFIG_USB_OTG
#define CONFIG_USB_ARCH_HAS_HCD 1
#define CONFIG_USB_ARCH_HAS_OHCI 1

/*
 * USB Host Controller Drivers
 */
#define CONFIG_USB_EHCI_HCD 1
#undef CONFIG_USB_EHCI_SPLIT_ISO
#undef CONFIG_USB_EHCI_ROOT_HUB_TT
#define CONFIG_USB_OHCI_HCD 1
#define CONFIG_USB_UHCI_HCD 1
#define CONFIG_USB_SL811_HCD_MODULE 1

/*
 * USB Device Class drivers
 */
#undef CONFIG_USB_AUDIO

/*
 * USB Bluetooth TTY can only be used with disabled Bluetooth subsystem
 */
#undef CONFIG_USB_MIDI
#define CONFIG_USB_ACM_MODULE 1
#define CONFIG_USB_PRINTER_MODULE 1

/*
 * NOTE: USB_STORAGE enables SCSI, and 'SCSI disk support' may also be needed; see USB_STORAGE Help for more information
 */
#define CONFIG_USB_STORAGE_MODULE 1
#undef CONFIG_USB_STORAGE_DEBUG
#undef CONFIG_USB_STORAGE_RW_DETECT
#undef CONFIG_USB_STORAGE_DATAFAB
#undef CONFIG_USB_STORAGE_FREECOM
#undef CONFIG_USB_STORAGE_DPCM
#undef CONFIG_USB_STORAGE_HP8200e
#undef CONFIG_USB_STORAGE_SDDR09
#undef CONFIG_USB_STORAGE_SDDR55
#undef CONFIG_USB_STORAGE_JUMPSHOT

/*
 * USB Input Devices
 */
#define CONFIG_USB_HID 1
#define CONFIG_USB_HIDINPUT 1
#undef CONFIG_HID_FF
#define CONFIG_USB_HIDDEV 1
#undef CONFIG_USB_AIPTEK
#undef CONFIG_USB_WACOM
#undef CONFIG_USB_KBTAB
#undef CONFIG_USB_POWERMATE
#undef CONFIG_USB_MTOUCH
#undef CONFIG_USB_EGALAX
#undef CONFIG_USB_XPAD
#undef CONFIG_USB_ATI_REMOTE

/*
 * USB Imaging devices
 */
#undef CONFIG_USB_MDC800
#define CONFIG_USB_MICROTEK_MODULE 1

/*
 * USB Multimedia devices
 */
#undef CONFIG_USB_DABUSB
#undef CONFIG_USB_VICAM
#undef CONFIG_USB_DSBR
#undef CONFIG_USB_IBMCAM
#undef CONFIG_USB_KONICAWC
#undef CONFIG_USB_OV511
#undef CONFIG_USB_SE401
#undef CONFIG_USB_SN9C102
#undef CONFIG_USB_STV680

/*
 * USB Network Adapters
 */
#undef CONFIG_USB_CATC
#define CONFIG_USB_KAWETH_MODULE 1
#define CONFIG_USB_PEGASUS_MODULE 1
#undef CONFIG_USB_RTL8150
#define CONFIG_USB_USBNET_MODULE 1

/*
 * USB Host-to-Host Cables
 */
#define CONFIG_USB_ALI_M5632 1
#define CONFIG_USB_AN2720 1
#define CONFIG_USB_BELKIN 1
#define CONFIG_USB_GENESYS 1
#define CONFIG_USB_NET1080 1
#define CONFIG_USB_PL2301 1
#define CONFIG_USB_KC2190 1

/*
 * Intelligent USB Devices/Gadgets
 */
#define CONFIG_USB_ARMLINUX 1
#define CONFIG_USB_EPSON2888 1
#define CONFIG_USB_ZAURUS 1
#define CONFIG_USB_CDCETHER 1

/*
 * USB Network Adapters
 */

/*
 * USB port drivers
 */
#define CONFIG_USB_USS720_MODULE 1

/*
 * USB Serial Converter support
 */
#define CONFIG_USB_SERIAL 1
#undef CONFIG_USB_SERIAL_CONSOLE
#define CONFIG_USB_SERIAL_GENERIC 1
#define CONFIG_USB_SERIAL_BELKIN_MODULE 1
#define CONFIG_USB_SERIAL_DIGI_ACCELEPORT_MODULE 1
#undef CONFIG_USB_SERIAL_CYPRESS_M8
#define CONFIG_USB_SERIAL_EMPEG_MODULE 1
#undef CONFIG_USB_SERIAL_FTDI_SIO
#define CONFIG_USB_SERIAL_VISOR_MODULE 1
#define CONFIG_USB_SERIAL_IPAQ_MODULE 1
#undef CONFIG_USB_SERIAL_IR
#define CONFIG_USB_SERIAL_EDGEPORT_MODULE 1
#define CONFIG_USB_SERIAL_EDGEPORT_TI_MODULE 1
#define CONFIG_USB_SERIAL_GARMIN_MODULE 1
#undef CONFIG_USB_SERIAL_IPW
#define CONFIG_USB_SERIAL_KEYSPAN_PDA_MODULE 1
#define CONFIG_USB_SERIAL_KEYSPAN_MODULE 1
#undef CONFIG_USB_SERIAL_KEYSPAN_MPR
#undef CONFIG_USB_SERIAL_KEYSPAN_USA28
#undef CONFIG_USB_SERIAL_KEYSPAN_USA28X
#undef CONFIG_USB_SERIAL_KEYSPAN_USA28XA
#undef CONFIG_USB_SERIAL_KEYSPAN_USA28XB
#undef CONFIG_USB_SERIAL_KEYSPAN_USA19
#undef CONFIG_USB_SERIAL_KEYSPAN_USA18X
#undef CONFIG_USB_SERIAL_KEYSPAN_USA19W
#undef CONFIG_USB_SERIAL_KEYSPAN_USA19QW
#undef CONFIG_USB_SERIAL_KEYSPAN_USA19QI
#undef CONFIG_USB_SERIAL_KEYSPAN_USA49W
#undef CONFIG_USB_SERIAL_KEYSPAN_USA49WLC
#undef CONFIG_USB_SERIAL_KLSI
#define CONFIG_USB_SERIAL_KOBIL_SCT_MODULE 1
#define CONFIG_USB_SERIAL_MCT_U232_MODULE 1
#define CONFIG_USB_SERIAL_PL2303_MODULE 1
#undef CONFIG_USB_SERIAL_SAFE
#define CONFIG_USB_SERIAL_TI_MODULE 1
#undef CONFIG_USB_SERIAL_CYBERJACK
#define CONFIG_USB_SERIAL_XIRCOM_MODULE 1
#undef CONFIG_USB_SERIAL_OMNINET
#define CONFIG_USB_EZUSB 1

/*
 * USB Miscellaneous drivers
 */
#define CONFIG_USB_EMI62_MODULE 1
#define CONFIG_USB_EMI26_MODULE 1
#undef CONFIG_USB_AUERSWALD
#undef CONFIG_USB_RIO500
#undef CONFIG_USB_LEGOTOWER
#define CONFIG_USB_LCD_MODULE 1
#undef CONFIG_USB_LED
#undef CONFIG_USB_CYTHERM
#undef CONFIG_USB_PHIDGETKIT
#undef CONFIG_USB_PHIDGETSERVO
#define CONFIG_USB_IDMOUSE_MODULE 1

/*
 * USB ATM/DSL drivers
 */

/*
 * USB Gadget Support
 */
#undef CONFIG_USB_GADGET

/*
 * MMC/SD Card support
 */
#define CONFIG_MMC_MODULE 1
#undef CONFIG_MMC_DEBUG
#define CONFIG_MMC_BLOCK_MODULE 1

/*
 * InfiniBand support
 */
#define CONFIG_INFINIBAND_MODULE 1
#define CONFIG_INFINIBAND_MTHCA_MODULE 1
#define CONFIG_INFINIBAND_MTHCA_DEBUG 1
#define CONFIG_INFINIBAND_IPOIB_MODULE 1
#define CONFIG_INFINIBAND_IPOIB_DEBUG 1
#define CONFIG_INFINIBAND_IPOIB_DEBUG_DATA 1

/*
 * Firmware Drivers
 */
#undef CONFIG_EDD

/*
 * File systems
 */
#define CONFIG_EXT2_FS 1
#define CONFIG_EXT2_FS_XATTR 1
#define CONFIG_EXT2_FS_POSIX_ACL 1
#define CONFIG_EXT2_FS_SECURITY 1
#define CONFIG_EXT3_FS 1
#define CONFIG_EXT3_FS_XATTR 1
#define CONFIG_EXT3_FS_POSIX_ACL 1
#define CONFIG_EXT3_FS_SECURITY 1
#define CONFIG_JBD 1
#define CONFIG_JBD_DEBUG 1
#define CONFIG_FS_MBCACHE 1
#define CONFIG_REISERFS_FS_MODULE 1
#define CONFIG_REISERFS_CHECK 1
#define CONFIG_REISERFS_PROC_INFO 1
#define CONFIG_REISERFS_FS_XATTR 1
#define CONFIG_REISERFS_FS_POSIX_ACL 1
#define CONFIG_REISERFS_FS_SECURITY 1
#define CONFIG_JFS_FS_MODULE 1
#define CONFIG_JFS_POSIX_ACL 1
#define CONFIG_JFS_SECURITY 1
#undef CONFIG_JFS_DEBUG
#define CONFIG_JFS_STATISTICS 1
#define CONFIG_FS_POSIX_ACL 1

/*
 * XFS support
 */
#define CONFIG_XFS_FS_MODULE 1
#define CONFIG_XFS_EXPORT 1
#undef CONFIG_XFS_RT
#define CONFIG_XFS_QUOTA 1
#undef CONFIG_XFS_SECURITY
#define CONFIG_XFS_POSIX_ACL 1
#define CONFIG_MINIX_FS_MODULE 1
#define CONFIG_ROMFS_FS_MODULE 1
#define CONFIG_QUOTA 1
#undef CONFIG_QFMT_V1
#define CONFIG_QFMT_V2 1
#define CONFIG_QUOTACTL 1
#define CONFIG_DNOTIFY 1
#undef CONFIG_AUTOFS_FS
#define CONFIG_AUTOFS4_FS 1

/*
 * CD-ROM/DVD Filesystems
 */
#define CONFIG_ISO9660_FS_MODULE 1
#define CONFIG_JOLIET 1
#define CONFIG_ZISOFS 1
#define CONFIG_ZISOFS_FS_MODULE 1
#define CONFIG_UDF_FS_MODULE 1
#define CONFIG_UDF_NLS 1

/*
 * DOS/FAT/NT Filesystems
 */
#define CONFIG_FAT_FS_MODULE 1
#define CONFIG_MSDOS_FS_MODULE 1
#define CONFIG_VFAT_FS_MODULE 1
#define CONFIG_FAT_DEFAULT_CODEPAGE 437
#define CONFIG_FAT_DEFAULT_IOCHARSET "ascii"
#undef CONFIG_NTFS_FS

/*
 * Pseudo filesystems
 */
#define CONFIG_PROC_FS 1
#define CONFIG_PROC_KCORE 1
#define CONFIG_SYSFS 1
#undef CONFIG_DEVFS_FS
#undef CONFIG_DEVPTS_FS_XATTR
#define CONFIG_TMPFS 1
#define CONFIG_TMPFS_XATTR 1
#undef CONFIG_TMPFS_SECURITY
#define CONFIG_HUGETLBFS 1
#define CONFIG_HUGETLB_PAGE 1
#define CONFIG_RAMFS 1

/*
 * Miscellaneous filesystems
 */
#undef CONFIG_ADFS_FS
#undef CONFIG_AFFS_FS
#undef CONFIG_HFS_FS
#define CONFIG_HFSPLUS_FS_MODULE 1
#undef CONFIG_BEFS_FS
#undef CONFIG_BFS_FS
#undef CONFIG_EFS_FS
#undef CONFIG_JFFS_FS
#undef CONFIG_JFFS2_FS
#define CONFIG_CRAMFS_MODULE 1
#undef CONFIG_VXFS_FS
#undef CONFIG_HPFS_FS
#undef CONFIG_QNX4FS_FS
#define CONFIG_SYSV_FS_MODULE 1
#define CONFIG_UFS_FS_MODULE 1
#undef CONFIG_UFS_FS_WRITE

/*
 * Network File Systems
 */
#define CONFIG_NFS_FS_MODULE 1
#undef CONFIG_NFS_V3
#undef CONFIG_NFS_V4
#undef CONFIG_NFS_DIRECTIO
#define CONFIG_NFSD_MODULE 1
#define CONFIG_NFSD_V3 1
#undef CONFIG_NFSD_V4
#define CONFIG_NFSD_TCP 1
#define CONFIG_LOCKD_MODULE 1
#define CONFIG_LOCKD_V4 1
#define CONFIG_EXPORTFS_MODULE 1
#define CONFIG_SUNRPC_MODULE 1
#undef CONFIG_RPCSEC_GSS_KRB5
#undef CONFIG_RPCSEC_GSS_SPKM3
#undef CONFIG_SMB_FS
#define CONFIG_CIFS_MODULE 1
#define CONFIG_CIFS_STATS 1
#define CONFIG_CIFS_XATTR 1
#define CONFIG_CIFS_POSIX 1
#undef CONFIG_CIFS_EXPERIMENTAL
#define CONFIG_NCP_FS_MODULE 1
#define CONFIG_NCPFS_PACKET_SIGNING 1
#define CONFIG_NCPFS_IOCTL_LOCKING 1
#define CONFIG_NCPFS_STRONG 1
#define CONFIG_NCPFS_NFS_NS 1
#define CONFIG_NCPFS_OS2_NS 1
#define CONFIG_NCPFS_SMALLDOS 1
#define CONFIG_NCPFS_NLS 1
#define CONFIG_NCPFS_EXTRAS 1
#define CONFIG_CODA_FS_MODULE 1
#undef CONFIG_CODA_FS_OLD_API
#undef CONFIG_AFS_FS

/*
 * Partition Types
 */
#define CONFIG_PARTITION_ADVANCED 1
#undef CONFIG_ACORN_PARTITION
#define CONFIG_OSF_PARTITION 1
#define CONFIG_AMIGA_PARTITION 1
#undef CONFIG_ATARI_PARTITION
#define CONFIG_MAC_PARTITION 1
#define CONFIG_MSDOS_PARTITION 1
#define CONFIG_BSD_DISKLABEL 1
#define CONFIG_MINIX_SUBPARTITION 1
#define CONFIG_SOLARIS_X86_PARTITION 1
#define CONFIG_UNIXWARE_DISKLABEL 1
#define CONFIG_LDM_PARTITION 1
#undef CONFIG_LDM_DEBUG
#define CONFIG_SGI_PARTITION 1
#undef CONFIG_ULTRIX_PARTITION
#define CONFIG_SUN_PARTITION 1
#define CONFIG_EFI_PARTITION 1

/*
 * Native Language Support
 */
#define CONFIG_NLS 1
#define CONFIG_NLS_DEFAULT "utf8"
#define CONFIG_NLS_CODEPAGE_437 1
#define CONFIG_NLS_CODEPAGE_737_MODULE 1
#define CONFIG_NLS_CODEPAGE_775_MODULE 1
#define CONFIG_NLS_CODEPAGE_850_MODULE 1
#define CONFIG_NLS_CODEPAGE_852_MODULE 1
#define CONFIG_NLS_CODEPAGE_855_MODULE 1
#define CONFIG_NLS_CODEPAGE_857_MODULE 1
#define CONFIG_NLS_CODEPAGE_860_MODULE 1
#define CONFIG_NLS_CODEPAGE_861_MODULE 1
#define CONFIG_NLS_CODEPAGE_862_MODULE 1
#define CONFIG_NLS_CODEPAGE_863_MODULE 1
#define CONFIG_NLS_CODEPAGE_864_MODULE 1
#define CONFIG_NLS_CODEPAGE_865_MODULE 1
#define CONFIG_NLS_CODEPAGE_866_MODULE 1
#define CONFIG_NLS_CODEPAGE_869_MODULE 1
#define CONFIG_NLS_CODEPAGE_936_MODULE 1
#define CONFIG_NLS_CODEPAGE_950_MODULE 1
#define CONFIG_NLS_CODEPAGE_932_MODULE 1
#define CONFIG_NLS_CODEPAGE_949_MODULE 1
#define CONFIG_NLS_CODEPAGE_874_MODULE 1
#define CONFIG_NLS_ISO8859_8_MODULE 1
#define CONFIG_NLS_CODEPAGE_1250_MODULE 1
#define CONFIG_NLS_CODEPAGE_1251_MODULE 1
#define CONFIG_NLS_ASCII 1
#define CONFIG_NLS_ISO8859_1_MODULE 1
#define CONFIG_NLS_ISO8859_2_MODULE 1
#define CONFIG_NLS_ISO8859_3_MODULE 1
#define CONFIG_NLS_ISO8859_4_MODULE 1
#define CONFIG_NLS_ISO8859_5_MODULE 1
#define CONFIG_NLS_ISO8859_6_MODULE 1
#define CONFIG_NLS_ISO8859_7_MODULE 1
#define CONFIG_NLS_ISO8859_9_MODULE 1
#define CONFIG_NLS_ISO8859_13_MODULE 1
#define CONFIG_NLS_ISO8859_14_MODULE 1
#define CONFIG_NLS_ISO8859_15_MODULE 1
#define CONFIG_NLS_KOI8_R_MODULE 1
#define CONFIG_NLS_KOI8_U_MODULE 1
#define CONFIG_NLS_UTF8_MODULE 1

/*
 * Profiling support
 */
#undef CONFIG_PROFILING

/*
 * Kernel hacking
 */
#define CONFIG_DEBUG_KERNEL 1
#define CONFIG_MAGIC_SYSRQ 1
#define CONFIG_SCHEDSTATS 1
#define CONFIG_DEBUG_SLAB 1
#define CONFIG_DEBUG_PREEMPT 1
#define CONFIG_DEBUG_SPINLOCK 1
#define CONFIG_DEBUG_SPINLOCK_SLEEP 1
#define CONFIG_DEBUG_KOBJECT 1
#define CONFIG_DEBUG_INFO 1
#define CONFIG_DEBUG_FS 1
#define CONFIG_INIT_DEBUG 1
#define CONFIG_IOMMU_DEBUG 1
#define CONFIG_KPROBES 1
#define CONFIG_IOMMU_LEAK 1

/*
 * Security options
 */
#define CONFIG_KEYS 1
#undef CONFIG_KEYS_DEBUG_PROC_KEYS
#define CONFIG_SECURITY 1
#define CONFIG_SECURITY_NETWORK 1
#undef CONFIG_SECURITY_CAPABILITIES
#undef CONFIG_SECURITY_ROOTPLUG
#undef CONFIG_SECURITY_SECLVL
#define CONFIG_SECURITY_SELINUX 1
#define CONFIG_SECURITY_SELINUX_BOOTPARAM 1
#define CONFIG_SECURITY_SELINUX_BOOTPARAM_VALUE 1
#define CONFIG_SECURITY_SELINUX_DISABLE 1
#define CONFIG_SECURITY_SELINUX_DEVELOP 1
#define CONFIG_SECURITY_SELINUX_AVC_STATS 1
#undef CONFIG_SECURITY_SELINUX_MLS

/*
 * Cryptographic options
 */
#define CONFIG_CRYPTO 1
#define CONFIG_CRYPTO_HMAC 1
#define CONFIG_CRYPTO_NULL 1
#define CONFIG_CRYPTO_MD4_MODULE 1
#define CONFIG_CRYPTO_MD5 1
#define CONFIG_CRYPTO_SHA1 1
#define CONFIG_CRYPTO_SHA256 1
#define CONFIG_CRYPTO_SHA512_MODULE 1
#define CONFIG_CRYPTO_WP512_MODULE 1
#define CONFIG_CRYPTO_DES_MODULE 1
#define CONFIG_CRYPTO_BLOWFISH_MODULE 1
#define CONFIG_CRYPTO_TWOFISH_MODULE 1
#define CONFIG_CRYPTO_SERPENT_MODULE 1
#define CONFIG_CRYPTO_AES 1
#define CONFIG_CRYPTO_CAST5_MODULE 1
#define CONFIG_CRYPTO_CAST6_MODULE 1
#define CONFIG_CRYPTO_TEA_MODULE 1
#define CONFIG_CRYPTO_ARC4_MODULE 1
#define CONFIG_CRYPTO_KHAZAD_MODULE 1
#define CONFIG_CRYPTO_ANUBIS_MODULE 1
#define CONFIG_CRYPTO_DEFLATE_MODULE 1
#define CONFIG_CRYPTO_MICHAEL_MIC_MODULE 1
#define CONFIG_CRYPTO_CRC32C 1
#define CONFIG_CRYPTO_TEST_MODULE 1

/*
 * Hardware crypto devices
 */

/*
 * Library routines
 */
#define CONFIG_CRC_CCITT 1
#define CONFIG_CRC32 1
#define CONFIG_LIBCRC32C 1
#define CONFIG_ZLIB_INFLATE_MODULE 1
#define CONFIG_ZLIB_DEFLATE_MODULE 1
